### ISSUE TITLE
Add-SPDistributedCache  has identical parameters for SP SE, SP 2019, SP 2016, but the article is scoped only for SPSE,

### ISSUE THREAD

**Issue by rainerasbach** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#71] opened 2021-11-08 12:26 UTC
Add-SPDistributedCache  has identical parameters for SP SE, SP 2019, SP 2016, but the article is scoped only for SPSE, please add SP 2019 and SP 2016 as additional product versions for this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfdc3ce-d41e-7110-94f0-158493149ab9
* Version Independent ID: 778d4ad6-de3a-4e9a-3b7d-339a9181b809
* Content: [Add-SPDistributedCacheServiceInstance (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/add-spdistributedcacheserviceinstance?view=sharepoint-server-ps)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/Add-SPDistributedCacheServiceInstance.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Add-SPDistributedCacheServiceInstance.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by tseward** [comment] 2021-11-08 15:17
@WayneEwington this actually looks to be a systemic problem -- I checked a handful of cmdlets and they've all been changed to SPSE only, even though they apply to 2010+.

**Comment by WayneEwington** [comment] 2021-11-08 17:25
I'm not the owner of the on-premises PowerShell cmdlets. Adding @TroyStarr to investigate

**Comment by TroyStarr** [comment] 2021-11-09 00:24
Hey folks, this is by design.  We've split the SharePoint Server PowerShell cmdlet documentation into two separate repositories.  One repository is for [SharePoint Server Subscription Edition](https://docs.microsoft.com/powershell/module/sharepoint-server/?view=sharepoint-server-ps) (which we expect to evolve over time with additional cmdlets and parameters) and the other is for [SharePoint 2010 - 2019](https://docs.microsoft.com/powershell/module/sharepoint-server/?view=sharepoint-ps).  You can switch between them using the Version selector on the left side of the articles.  That said, I think we can make that clearer in the Version selector options so I'll follow up with the team to ask them to do that.

**Comment by tseward** [comment] 2021-11-09 00:44
@TroyStarr could we rephrase "Latest" to 2010-2019 or something akin to that? This is confusing.

![image](https://user-images.githubusercontent.com/7698997/140840951-bf0f5c1d-352f-414c-8d9b-01cd01149773.png)

**Comment by TroyStarr** [comment] 2021-11-09 00:45
Yep, agreed. :-)

**Comment by get-itips** [comment] 2021-11-16 12:43
> Yep, agreed. :-)

Hello @TroyStarr Troy, are you able to make @tseward 's suggested change? Thanks for clarifying

**Comment by TroyStarr** [comment] 2021-11-16 13:15
Hi @get-itips, we're discussing our options with our PowerShell repo contacts. There are some complications because the SharePoint Server (2010 - 2019), SharePoint Online, and SharePoint PnP PowerShell articles are currently grouped together as the single "Latest" choice in the version selector. No ETA yet on when we'll have a solution for moving forward.

**Comment by get-itips** [comment] 2021-11-16 13:17
> Hi @get-itips, we're discussing our options with our PowerShell repo contacts. There are some complications because the SharePoint Server (2010 - 2019), SharePoint Online, and SharePoint PnP PowerShell articles are currently grouped together as the single "Latest" choice in the version selector. No ETA yet on when we'll have a solution for moving forward.

Thanks for the detailed update ;)

**Comment by tiburd** [comment] 2021-11-16 21:07
Because the appropriate team members are aware of this issue and are working on a solution, we're closing this issue.

Thank you, all!

**Closed by tiburd** 2021-11-16 21:07 UTC
Labels: writer-input-required
