### ISSUE TITLE
Missing Details on Loop Sharing

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#182] opened 2022-03-08 17:06 UTC
This needs details on the following parameters

OneDriveLoopSharingCapability 
CoreLoopSharingCapability 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment] 2022-03-29 04:35
Closing as duplicate of #197

**Closed** 2022-03-29 04:35 UTC
Labels: duplicate
